CREATE DATABASE NewsAppDB;

CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Age INT NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    Password VARBINARY(MAX) NOT NULL,
    SessionToken NVARCHAR(100) NULL

);

SELECT * FROM Users;

DROP TABLE Users;

